### ISSUE TITLE
File upload failed  but updates usage statistics

### ISSUE THREAD

**Issue by rubensmau** [eugeneyan/align-app#1]
I have cloned your app ( both in WSL and Windows ) and got the same error, when trying to upload a file.
Repeated the test using different browsers.

Got the error message on the browser : Failed to upload file. Please try again  .
In the server side got the error 
Error processing upload: [Error: SQLITE_ERROR: near "FROM": syntax error] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
 POST /api/upload 500 in 36ms

However the statistics were updated and shown on screed after a page reload . However I got no button to proceed .

**Comment by eugeneyan** [comment]
Yea the support for SQLite is likely broken—it was too difficult to have queries that worked well for SQLite and Postgres. Would you be able to try with a local instance of Postgres instead? I'ved added a [sample env file](https://github.com/eugeneyan/align-app/blob/main/.env.local) for reference.

Alternatively, the error is probably due to this [line](https://github.com/eugeneyan/align-app/blob/main/app/lib/actions.ts#L15), where you need to change it for SQLite like so:

```sql
SELECT EXISTS (
    SELECT 1 FROM sqlite_master 
    WHERE type='table' 
    AND name = ?
);
```

**Comment by rubensmau** [comment]
yes, using Postgres solved the problem.
